### ISSUE TITLE
Can’t change volume

### ISSUE THREAD

**Issue by nak0604** [iKilledAppl3/RishimaBugReports#1]
No matter how much I press the volume button I can’t change it. The only way to change the volume is to go into control center and manually Change it.

iPhone XS Max 12.1.1 beta 3
![11E75BBE-C17F-4AB3-BFC2-11D8E37D1B5E](https://user-images.githubusercontent.com/4227228/59466789-25628780-8dfc-11e9-8baf-7a5a3c5d168f.png)

**Comment by iKilledAppl3** [comment]
Any tweaks that modify the control center installed?

**Comment by nak0604** [comment]
Nope

**Comment by iKilledAppl3** [comment]
Ok so I think I may know the issue is adjust ringer volume with buttons on in your sound settings for your iPhone? ![Image](https://i.imgur.com/THenmUO.jpg)

**Comment by nak0604** [comment]
That’s turned on as well

**Comment by iKilledAppl3** [comment]
try turning that off for now. I'm working on this issue as we speak
