### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by theb1g0ne** [iKilledAppl3/RishimaBugReports#3]
Crashes springboard (safe mode) after installing

**Comment by iKilledAppl3** [comment]
Please send a detail crash log can't help without one. Also if you have another tweak that modifies the volume hud or a tweak that modifies the Control Center please let me know the name's of these.

**Comment by theb1g0ne** [comment]
BetterCCXI, CCSupport, FlipConvert
Jesse Huelbig
@theb1g0ne
